# Generated by Django 4.2.6 on 2023-12-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0036_alter_videorecognition_voice_emotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyzePDF',
        ),
        migrations.DeleteModel(
            name='ImageRecognition',
        ),
    ]
