# Generated by Django 5.0 on 2024-01-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0052_frame_current_time_frame_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecognition',
            name='analysis_score',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
